import { readFile, writeFile } from 'node:fs/promises';

const guide = await readFile(new URL('./guide.txt', import.meta.url), 'utf8');
const code = `// Generated by node website/build.mjs from guide.txt.
const guide = ${JSON.stringify(guide)};
export default {
  async fetch(request) {
    const path = new URL(request.url).pathname;
    if (path !== '/capcut' && !path.startsWith('/capcut/')) return fetch(request);
    const headers = {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'Content-Security-Policy': "default-src 'none'; base-uri 'none'; frame-ancestors 'none'",
    };
    if (!['GET', 'HEAD'].includes(request.method)) {
      return new Response('Method not allowed', { status: 405, headers: { ...headers, Allow: 'GET, HEAD' } });
    }
    const found = ['/capcut', '/capcut/', '/capcut/install.txt'].includes(path);
    const body = request.method === 'HEAD' ? null : found ? guide : 'Not found';
    return new Response(body, { status: found ? 200 : 404, headers });
  },
};
`;
await writeFile(new URL('./worker.mjs', import.meta.url), code);
